### ISSUE TITLE
Fix broken image link to open likelihood news item

### ISSUE THREAD

**Issue by msneubauer** [Neubauer-Group/neubauer-group.github.io#12]
This link was used in the image for the news item:

https://atlas-public.web.cern.ch/sites/atlas-public.web.cern.ch/files/field/image/ATLAS-OpenLikelihoods-Mockup.jpg

It no longer exists. 

Suggest finding an appropriate image file and adding into the images/newspic folder.

**Comment by matthewfeickert** [comment]
Was able to search on the specific image name to find it again on CDS under [ATLAS News: Open Likelihoods on HEPData](https://cds.cern.ch/record/2705831/)

[![ATLAS-OpenLikelihoods-Mockup](https://cds.cern.ch/record/2705831/files/ATLAS-OpenLikelihoods-Mockup.jpg)](https://cds.cern.ch/record/2705831/)

While CDS should be stable, I'll take a reasonably sized version of it and add it to the website binaries.
